spring:
  application:
    name: 'transaction-limits-service'
  profiles:
    active: 'local'

  data:
    web:
      pageable:
        default-page-size: '5'
        max-page-size: '50'
        one-indexed-parameters: 'true'
  datasource:
    driverClassName: 'org.postgresql.Driver'
    hikari:
      maximum-pool-size: '20'

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'validate'
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: 'app'

  liquibase:
    enabled: 'true'
    change-log: 'classpath:/db/changelog/db.changelog-master.yml'
    default-schema: 'app'

logging:
  level:
    root: 'info'

#Custom properties
app:
  property:
    limitsByDefault:
      product: '1000'
      service: '1000'

clients:
  currency:
    twelve-data:
      url: 'https://api.twelvedata.com'
      property:
        api-key: 'ff397938127745699ebc085d8ad580cc'
        interval: '1day'
        output-size: '1'
        previous-close: 'true'

